/*******************************************************************************
  Pin Bit Position Definitions

  Company:
    DAQiFi

  File Name:
    pin_definitions.h

  Summary:
    Additional pin definitions for board configuration

  Description:
    This file provides PORT_CHANNEL and PORTS_BIT_POS style definitions
    to complement the MCC-generated plib_gpio.h macros. This file is NOT
    generated by MCC and should be manually maintained.

    Harmony 2.x (bootloader) auto-generated these macros, but Harmony 3 does not.
    This provides compatibility and cleaner board configuration code.

*******************************************************************************/

#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#include "plib_gpio.h"

// *****************************************************************************
// Port channel aliases (match GPIO_PORT values from plib_gpio.h)
// *****************************************************************************
#define PORT_CHANNEL_A  GPIO_PORT_A
#define PORT_CHANNEL_B  GPIO_PORT_B
#define PORT_CHANNEL_C  GPIO_PORT_C
#define PORT_CHANNEL_D  GPIO_PORT_D
#define PORT_CHANNEL_E  GPIO_PORT_E
#define PORT_CHANNEL_F  GPIO_PORT_F
#define PORT_CHANNEL_G  GPIO_PORT_G
#define PORT_CHANNEL_H  GPIO_PORT_H
#define PORT_CHANNEL_J  GPIO_PORT_J
#define PORT_CHANNEL_K  GPIO_PORT_K

// *****************************************************************************
// Bit position definitions (0-15)
// These represent the bit position within a port register for bitshift operations
// *****************************************************************************
#define PORTS_BIT_POS_0   0
#define PORTS_BIT_POS_1   1
#define PORTS_BIT_POS_2   2
#define PORTS_BIT_POS_3   3
#define PORTS_BIT_POS_4   4
#define PORTS_BIT_POS_5   5
#define PORTS_BIT_POS_6   6
#define PORTS_BIT_POS_7   7
#define PORTS_BIT_POS_8   8
#define PORTS_BIT_POS_9   9
#define PORTS_BIT_POS_10  10
#define PORTS_BIT_POS_11  11
#define PORTS_BIT_POS_12  12
#define PORTS_BIT_POS_13  13
#define PORTS_BIT_POS_14  14
#define PORTS_BIT_POS_15  15

#endif /* PIN_DEFINITIONS_H */
