/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DAQIFIOUTMESSAGE_PB_H_INCLUDED
#define PB_DAQIFIOUTMESSAGE_PB_H_INCLUDED
#include "libraries/nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(2) DaqifiOutMessage_digital_data_t;
typedef PB_BYTES_ARRAY_T(16) DaqifiOutMessage_analog_in_port_type_t;
typedef PB_BYTES_ARRAY_T(2) DaqifiOutMessage_analog_in_port_av_rse_t;
typedef PB_BYTES_ARRAY_T(2) DaqifiOutMessage_analog_in_port_rse_t;
typedef PB_BYTES_ARRAY_T(2) DaqifiOutMessage_analog_in_port_enabled_t;
typedef PB_BYTES_ARRAY_T(16) DaqifiOutMessage_digital_port_type_t;
typedef PB_BYTES_ARRAY_T(2) DaqifiOutMessage_digital_port_dir_t;
typedef PB_BYTES_ARRAY_T(16) DaqifiOutMessage_analog_out_port_type_t;
typedef PB_BYTES_ARRAY_T(4) DaqifiOutMessage_ip_addr_t;
typedef PB_BYTES_ARRAY_T(4) DaqifiOutMessage_net_mask_t;
typedef PB_BYTES_ARRAY_T(4) DaqifiOutMessage_gateway_t;
typedef PB_BYTES_ARRAY_T(4) DaqifiOutMessage_primary_dns_t;
typedef PB_BYTES_ARRAY_T(4) DaqifiOutMessage_secondary_dns_t;
typedef PB_BYTES_ARRAY_T(6) DaqifiOutMessage_mac_addr_t;
typedef PB_BYTES_ARRAY_T(16) DaqifiOutMessage_ip_addr_v6_t;
typedef PB_BYTES_ARRAY_T(1) DaqifiOutMessage_sub_pre_length_v6_t;
typedef PB_BYTES_ARRAY_T(16) DaqifiOutMessage_gateway_v6_t;
typedef PB_BYTES_ARRAY_T(16) DaqifiOutMessage_primary_dns_v6_t;
typedef PB_BYTES_ARRAY_T(16) DaqifiOutMessage_secondary_dns_v6_t;
typedef PB_BYTES_ARRAY_T(8) DaqifiOutMessage_eui_64_t;
typedef struct _DaqifiOutMessage { /* Put repetitive information in first 15 fields to keep encoded data as short as possible */
    /* Begin streaming data */
    uint32_t msg_time_stamp; /* Incrementing timestamp for each streaming trigger (frequency=timestamp_freq) */
    pb_size_t analog_in_data_count;
    int32_t analog_in_data[16]; /* Analog in data int (maximum 24bit/ch) (available to user) */
    pb_size_t analog_in_data_float_count;
    float analog_in_data_float[16]; /* Analog in data float (after cal calcs)(available to user) */
    pb_size_t analog_in_data_ts_count;
    uint32_t analog_in_data_ts[16]; /* Analog in data timestamp offset (value should be added to msg_time_stamp for absolute timestamp) */
    DaqifiOutMessage_digital_data_t digital_data; /* Digital IO data (bitwise binary representation LSB=ch0) */
    pb_size_t digital_data_ts_count;
    uint32_t digital_data_ts[16]; /* Digital IO data timestamp offset (value should be added to msg_time_stamp for absolute timestamp) */
    pb_size_t analog_out_data_count;
    uint16_t analog_out_data[8]; /* Analog out data int (maximum 12bit/ch) */
    uint32_t device_status; /* Device status word */
    uint32_t pwr_status; /* Power status */
    uint8_t batt_status; /* Battery charge percent */
    int32_t temp_status; /* Board temperature in deg C */
    uint32_t timestamp_freq; /* Frequency of the timestamp counter */
    /* Analog In Information */
    uint32_t analog_in_port_num; /* Number of analog in ports (public) */
    uint32_t analog_in_port_num_priv; /* Number of analog in ports (private) */
    DaqifiOutMessage_analog_in_port_type_t analog_in_port_type; /* Analog in port type */
    DaqifiOutMessage_analog_in_port_av_rse_t analog_in_port_av_rse; /* Analog in port referenced single ended (RSE) */
    DaqifiOutMessage_analog_in_port_rse_t analog_in_port_rse; /* Analog in port referenced single ended (RSE) */
    DaqifiOutMessage_analog_in_port_enabled_t analog_in_port_enabled; /* Analog in port enabled list */
    pb_size_t analog_in_port_av_range_count;
    float analog_in_port_av_range[2]; /* Analog in port voltage range (volts span:RSE 0 to range, NON-RSE -(range/2) to (range/2)) */
    pb_size_t analog_in_port_av_range_priv_count;
    float analog_in_port_av_range_priv[1]; /* Private analog in port voltage range (volts span:RSE 0 to range, NON-RSE -(range/2) to (range/2)) */
    pb_size_t analog_in_port_range_count;
    float analog_in_port_range[16]; /* Analog in port voltage range (volts span:RSE 0 to range, NON-RSE -(range/2) to (range/2)) */
    pb_size_t analog_in_port_range_priv_count;
    float analog_in_port_range_priv[8]; /* Private analog in port voltage range (volts span:RSE 0 to range, NON-RSE -(range/2) to (range/2)) */
    uint32_t analog_in_res; /* Public analog in (ADC) resolution (bits used to convert from integer value to volts) */
    uint32_t analog_in_res_priv; /* Private analog in (ADC) resolution (bits used to convert from integer value to volts) */
    pb_size_t analog_in_int_scale_m_count;
    float analog_in_int_scale_m[16]; /* Analog in port internal scale m value (should be applied to integer value before converting to volts) */
    pb_size_t analog_in_int_scale_m_priv_count;
    float analog_in_int_scale_m_priv[16]; /* Private analog in port internal scale m value (should be applied to integer value before converting to volts) */
    pb_size_t analog_in_cal_m_count;
    float analog_in_cal_m[16]; /* Analog in port calibration m value (should be applied to integer value before converting to volts) */
    pb_size_t analog_in_cal_b_count;
    float analog_in_cal_b[16]; /* Analog in port calibration b value (should be applied to integer value before converting to volts) */
    pb_size_t analog_in_cal_m_priv_count;
    float analog_in_cal_m_priv[8]; /* Private analog in port calibration m value (should be applied to integer value before converting to volts) */
    pb_size_t analog_in_cal_b_priv_count;
    float analog_in_cal_b_priv[8]; /* Private analog in port calibration b value (should be applied to integer value before converting to volts) */
    /* Digital I/O Information */
    uint32_t digital_port_num; /* Number of digital IO ports (public) */
    DaqifiOutMessage_digital_port_type_t digital_port_type; /* Digital IP port type */
    DaqifiOutMessage_digital_port_dir_t digital_port_dir; /* Digital IO port direction (bitwise binary representation LSB=ch0) */
    /* Analog Out Information */
    uint32_t analog_out_port_num; /* Number of analog out ports (DAC) */
    DaqifiOutMessage_analog_out_port_type_t analog_out_port_type; /* Type of analog out port (DAC) */
    uint32_t analog_out_res; /* Analog out port (DAC) resolution (bits) */
    pb_size_t analog_out_port_av_range_count;
    float analog_out_port_av_range[1]; /* Analog out port available range (volts span: 0 to range) (DAC) */
    float analog_out_port_range; /* Analog out port range (volts span: 0 to range) (DAC) */
    /* IPv4 Device Information */
    DaqifiOutMessage_ip_addr_t ip_addr; /* Device IP address */
    DaqifiOutMessage_net_mask_t net_mask; /* Network mask */
    DaqifiOutMessage_gateway_t gateway; /* Default gateway */
    DaqifiOutMessage_primary_dns_t primary_dns; /* Primary DNS */
    DaqifiOutMessage_secondary_dns_t secondary_dns; /* Secondary DNS */
    DaqifiOutMessage_mac_addr_t mac_addr; /* Device MAC address */
    /* IPv6 Device Information */
    DaqifiOutMessage_ip_addr_v6_t ip_addr_v6; /* Device IP address v6 */
    DaqifiOutMessage_sub_pre_length_v6_t sub_pre_length_v6; /* Subnet prefix length v6 */
    DaqifiOutMessage_gateway_v6_t gateway_v6; /* Default gateway v6 */
    DaqifiOutMessage_primary_dns_v6_t primary_dns_v6; /* Primary DNS v6 */
    DaqifiOutMessage_secondary_dns_v6_t secondary_dns_v6; /* Secondary DNS v6 */
    DaqifiOutMessage_eui_64_t eui_64; /* Device EUI-64 address */
    /* Device Network Information */
    char host_name[34]; /* Device HostName */
    uint32_t device_port; /* Device port */
    char friendly_device_name[32]; /* Device friendly name */
    char ssid[34]; /* Current SSID device is to connect to */
    uint32_t ssid_strength; /* Current SSID strength out of 255 */
    uint8_t wifi_security_mode; /* Device WiFi security mode */
    uint32_t wifi_inf_mode; /* Current SSID infrastructure mode */
    /* Aviable Network Information */
    pb_size_t av_ssid_count;
    char av_ssid[8][34]; /* Available SSIDs to connect to */
    pb_size_t av_ssid_strength_count;
    uint32_t av_ssid_strength[8]; /* Available SSID strength out of 255 */
    pb_size_t av_wifi_security_mode_count;
    uint32_t av_wifi_security_mode[8]; /* Available WiFi network security mode */
    pb_size_t av_wifi_inf_mode_count;
    uint32_t av_wifi_inf_mode[8]; /* Available WiFi network infrastructure mode */
    /* Device Hardware/Firmware Information */
    char device_pn[16]; /* Alphanumeric device P/N */
    char device_hw_rev[16]; /* Device hardware revision */
    char device_fw_rev[16]; /* Device firmware revision */
    uint64_t device_sn; /* Device serial number */
} DaqifiOutMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DaqifiOutMessage_init_default            {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, {0, 0}, 0, {0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, {0}}, {0, {0}}, 0, {0, {0}}, 0, 0, {0}, 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, "", 0, "", "", 0, 0, 0, 0, {"", "", "", "", "", "", "", ""}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, "", "", "", 0}
#define DaqifiOutMessage_init_zero               {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, {0, 0}, 0, {0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, {0}}, {0, {0}}, 0, {0, {0}}, 0, 0, {0}, 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, "", 0, "", "", 0, 0, 0, 0, {"", "", "", "", "", "", "", ""}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, "", "", "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define DaqifiOutMessage_msg_time_stamp_tag      1
#define DaqifiOutMessage_analog_in_data_tag      2
#define DaqifiOutMessage_analog_in_data_float_tag 3
#define DaqifiOutMessage_analog_in_data_ts_tag   4
#define DaqifiOutMessage_digital_data_tag        5
#define DaqifiOutMessage_digital_data_ts_tag     6
#define DaqifiOutMessage_analog_out_data_tag     7
#define DaqifiOutMessage_device_status_tag       8
#define DaqifiOutMessage_pwr_status_tag          9
#define DaqifiOutMessage_batt_status_tag         10
#define DaqifiOutMessage_temp_status_tag         11
#define DaqifiOutMessage_timestamp_freq_tag      16
#define DaqifiOutMessage_analog_in_port_num_tag  17
#define DaqifiOutMessage_analog_in_port_num_priv_tag 18
#define DaqifiOutMessage_analog_in_port_type_tag 19
#define DaqifiOutMessage_analog_in_port_av_rse_tag 20
#define DaqifiOutMessage_analog_in_port_rse_tag  21
#define DaqifiOutMessage_analog_in_port_enabled_tag 22
#define DaqifiOutMessage_analog_in_port_av_range_tag 23
#define DaqifiOutMessage_analog_in_port_av_range_priv_tag 24
#define DaqifiOutMessage_analog_in_port_range_tag 25
#define DaqifiOutMessage_analog_in_port_range_priv_tag 26
#define DaqifiOutMessage_analog_in_res_tag       27
#define DaqifiOutMessage_analog_in_res_priv_tag  28
#define DaqifiOutMessage_analog_in_int_scale_m_tag 29
#define DaqifiOutMessage_analog_in_int_scale_m_priv_tag 30
#define DaqifiOutMessage_analog_in_cal_m_tag     31
#define DaqifiOutMessage_analog_in_cal_b_tag     32
#define DaqifiOutMessage_analog_in_cal_m_priv_tag 33
#define DaqifiOutMessage_analog_in_cal_b_priv_tag 34
#define DaqifiOutMessage_digital_port_num_tag    35
#define DaqifiOutMessage_digital_port_type_tag   36
#define DaqifiOutMessage_digital_port_dir_tag    37
#define DaqifiOutMessage_analog_out_port_num_tag 38
#define DaqifiOutMessage_analog_out_port_type_tag 39
#define DaqifiOutMessage_analog_out_res_tag      40
#define DaqifiOutMessage_analog_out_port_av_range_tag 41
#define DaqifiOutMessage_analog_out_port_range_tag 42
#define DaqifiOutMessage_ip_addr_tag             43
#define DaqifiOutMessage_net_mask_tag            44
#define DaqifiOutMessage_gateway_tag             45
#define DaqifiOutMessage_primary_dns_tag         46
#define DaqifiOutMessage_secondary_dns_tag       47
#define DaqifiOutMessage_mac_addr_tag            48
#define DaqifiOutMessage_ip_addr_v6_tag          49
#define DaqifiOutMessage_sub_pre_length_v6_tag   50
#define DaqifiOutMessage_gateway_v6_tag          51
#define DaqifiOutMessage_primary_dns_v6_tag      52
#define DaqifiOutMessage_secondary_dns_v6_tag    53
#define DaqifiOutMessage_eui_64_tag              54
#define DaqifiOutMessage_host_name_tag           55
#define DaqifiOutMessage_device_port_tag         56
#define DaqifiOutMessage_friendly_device_name_tag 57
#define DaqifiOutMessage_ssid_tag                58
#define DaqifiOutMessage_ssid_strength_tag       59
#define DaqifiOutMessage_wifi_security_mode_tag  60
#define DaqifiOutMessage_wifi_inf_mode_tag       61
#define DaqifiOutMessage_av_ssid_tag             62
#define DaqifiOutMessage_av_ssid_strength_tag    63
#define DaqifiOutMessage_av_wifi_security_mode_tag 64
#define DaqifiOutMessage_av_wifi_inf_mode_tag    65
#define DaqifiOutMessage_device_pn_tag           66
#define DaqifiOutMessage_device_hw_rev_tag       67
#define DaqifiOutMessage_device_fw_rev_tag       68
#define DaqifiOutMessage_device_sn_tag           69

/* Struct field encoding specification for nanopb */
#define DaqifiOutMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msg_time_stamp,    1) \
X(a, STATIC,   REPEATED, SINT32,   analog_in_data,    2) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_data_float,   3) \
X(a, STATIC,   REPEATED, UINT32,   analog_in_data_ts,   4) \
X(a, STATIC,   SINGULAR, BYTES,    digital_data,      5) \
X(a, STATIC,   REPEATED, UINT32,   digital_data_ts,   6) \
X(a, STATIC,   REPEATED, UINT32,   analog_out_data,   7) \
X(a, STATIC,   SINGULAR, UINT32,   device_status,     8) \
X(a, STATIC,   SINGULAR, UINT32,   pwr_status,        9) \
X(a, STATIC,   SINGULAR, UINT32,   batt_status,      10) \
X(a, STATIC,   SINGULAR, SINT32,   temp_status,      11) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_freq,   16) \
X(a, STATIC,   SINGULAR, UINT32,   analog_in_port_num,  17) \
X(a, STATIC,   SINGULAR, UINT32,   analog_in_port_num_priv,  18) \
X(a, STATIC,   SINGULAR, BYTES,    analog_in_port_type,  19) \
X(a, STATIC,   SINGULAR, BYTES,    analog_in_port_av_rse,  20) \
X(a, STATIC,   SINGULAR, BYTES,    analog_in_port_rse,  21) \
X(a, STATIC,   SINGULAR, BYTES,    analog_in_port_enabled,  22) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_port_av_range,  23) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_port_av_range_priv,  24) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_port_range,  25) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_port_range_priv,  26) \
X(a, STATIC,   SINGULAR, UINT32,   analog_in_res,    27) \
X(a, STATIC,   SINGULAR, UINT32,   analog_in_res_priv,  28) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_int_scale_m,  29) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_int_scale_m_priv,  30) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_cal_m,  31) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_cal_b,  32) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_cal_m_priv,  33) \
X(a, STATIC,   REPEATED, FLOAT,    analog_in_cal_b_priv,  34) \
X(a, STATIC,   SINGULAR, UINT32,   digital_port_num,  35) \
X(a, STATIC,   SINGULAR, BYTES,    digital_port_type,  36) \
X(a, STATIC,   SINGULAR, BYTES,    digital_port_dir,  37) \
X(a, STATIC,   SINGULAR, UINT32,   analog_out_port_num,  38) \
X(a, STATIC,   SINGULAR, BYTES,    analog_out_port_type,  39) \
X(a, STATIC,   SINGULAR, UINT32,   analog_out_res,   40) \
X(a, STATIC,   REPEATED, FLOAT,    analog_out_port_av_range,  41) \
X(a, STATIC,   SINGULAR, FLOAT,    analog_out_port_range,  42) \
X(a, STATIC,   SINGULAR, BYTES,    ip_addr,          43) \
X(a, STATIC,   SINGULAR, BYTES,    net_mask,         44) \
X(a, STATIC,   SINGULAR, BYTES,    gateway,          45) \
X(a, STATIC,   SINGULAR, BYTES,    primary_dns,      46) \
X(a, STATIC,   SINGULAR, BYTES,    secondary_dns,    47) \
X(a, STATIC,   SINGULAR, BYTES,    mac_addr,         48) \
X(a, STATIC,   SINGULAR, BYTES,    ip_addr_v6,       49) \
X(a, STATIC,   SINGULAR, BYTES,    sub_pre_length_v6,  50) \
X(a, STATIC,   SINGULAR, BYTES,    gateway_v6,       51) \
X(a, STATIC,   SINGULAR, BYTES,    primary_dns_v6,   52) \
X(a, STATIC,   SINGULAR, BYTES,    secondary_dns_v6,  53) \
X(a, STATIC,   SINGULAR, BYTES,    eui_64,           54) \
X(a, STATIC,   SINGULAR, STRING,   host_name,        55) \
X(a, STATIC,   SINGULAR, UINT32,   device_port,      56) \
X(a, STATIC,   SINGULAR, STRING,   friendly_device_name,  57) \
X(a, STATIC,   SINGULAR, STRING,   ssid,             58) \
X(a, STATIC,   SINGULAR, UINT32,   ssid_strength,    59) \
X(a, STATIC,   SINGULAR, UINT32,   wifi_security_mode,  60) \
X(a, STATIC,   SINGULAR, UINT32,   wifi_inf_mode,    61) \
X(a, STATIC,   REPEATED, STRING,   av_ssid,          62) \
X(a, STATIC,   REPEATED, UINT32,   av_ssid_strength,  63) \
X(a, STATIC,   REPEATED, UINT32,   av_wifi_security_mode,  64) \
X(a, STATIC,   REPEATED, UINT32,   av_wifi_inf_mode,  65) \
X(a, STATIC,   SINGULAR, STRING,   device_pn,        66) \
X(a, STATIC,   SINGULAR, STRING,   device_hw_rev,    67) \
X(a, STATIC,   SINGULAR, STRING,   device_fw_rev,    68) \
X(a, STATIC,   SINGULAR, UINT64,   device_sn,        69)
#define DaqifiOutMessage_CALLBACK NULL
#define DaqifiOutMessage_DEFAULT NULL

extern const pb_msgdesc_t DaqifiOutMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DaqifiOutMessage_fields &DaqifiOutMessage_msg

/* Maximum encoded size of messages (where known) */
#define DAQIFIOUTMESSAGE_PB_H_MAX_SIZE           DaqifiOutMessage_size
#define DaqifiOutMessage_size                    2008

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
